name: test-python

on:
  pull_request:
    paths:
      - "**/*.py"

jobs:
  build:
    name: "test-python"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Fake Test
        run: echo "Fake Python test"
