version: 1.0.0
merge_rules:
  labels:
    trigger: mergequeue

scenarios:
- name: "instant merge"
  trigger:
    pull_request:
      labeled:
        label: "av-instant-merge"
  actions:
  - mergequeue:
      instant_merge: {}