name: Run linter

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   
    - name: Aviator Signals test
      uses: aviator-co/signals-action@v.0.1.43
      with:
        aviator-api-token: ${{ secrets.AVIATOR_API_TOKEN }}
        owner: 'aviator-testing-sa'
