name: Run linter

on: [push]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4   
    - name: Aviator Signals
      uses: aviator-co/signals-action@v.0.1.38
      with:
        AVIATOR_API_TOKEN: ${{ secrets.AVIATOR_API_TOKEN }}
